# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: website_status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf import base_pb2 as protobuf_dot_base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='website_status.proto',
  package='message',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14website_status.proto\x12\x07message\x1a\x13protobuf/base.proto\"\x7f\n\x0ewebsite_status\x12\x1c\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x0e.protobuf.base\x12\x12\n\nmonitor_id\x18\x02 \x01(\t\x12\x0f\n\x07website\x18\x03 \x01(\t\x12\x15\n\rresponse_time\x18\x04 \x01(\x05\x12\x13\n\x0bstatus_code\x18\x05 \x01(\x05\x62\x06proto3'
  ,
  dependencies=[protobuf_dot_base__pb2.DESCRIPTOR,])




_WEBSITE_STATUS = _descriptor.Descriptor(
  name='website_status',
  full_name='message.website_status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='message.website_status.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='monitor_id', full_name='message.website_status.monitor_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='website', full_name='message.website_status.website', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response_time', full_name='message.website_status.response_time', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='message.website_status.status_code', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=181,
)

_WEBSITE_STATUS.fields_by_name['base'].message_type = protobuf_dot_base__pb2._BASE
DESCRIPTOR.message_types_by_name['website_status'] = _WEBSITE_STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

website_status = _reflection.GeneratedProtocolMessageType('website_status', (_message.Message,), {
  'DESCRIPTOR' : _WEBSITE_STATUS,
  '__module__' : 'website_status_pb2'
  # @@protoc_insertion_point(class_scope:message.website_status)
  })
_sym_db.RegisterMessage(website_status)


# @@protoc_insertion_point(module_scope)
